server.port: 8080
spring:
  datasource:
    password: 12341234
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/setvin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000KB
      max-request-size: 5000KB       
  thymeleaf:
    cache: false
